### ISSUE TITLE
Float datatype for steering wheel angle values

### ISSUE THREAD

**Issue by cjmodi306** [eclipse-kuksa/kuksa-can-provider#28]
I am using the steering wheel angle data for a project however the int16 datatype leads to inaccuracies in my program. The preferred datatype would be float to gain the precise values. I tried changing it in VSS data but ultimately got int16 values anyway. Any help on this issue is much appreciated.

**Comment by lukasmittag** [comment]
can you provide your custom vss file? And the command you started the databroker with?

**Comment by cjmodi306** [comment]
[dbc_vspec.txt](https://github.com/user-attachments/files/16158378/dbc_vspec.txt) --> Please ignore the file extension; Github does not allow me to upload files with .vpec extension so I changed the extension to .txt.

Command for databroker:
```
docker run -it --rm --name Server --network host ghcr.io/eclipse/kuksa.val/databroker:master --insecure
```

**Comment by lukasmittag** [comment]
Yes, you need to create a new json file that goes into databroker. Else it takes a default one. For this you need to mount a volume in the docker container by specifying `-v source:destination`. Add after `--insceure` `--metadata destination/yourjsonfile.json`. You need to take the vspec file and generate a json file. For this use `vss-tools` https://covesa.github.io/vehicle_signal_specification/ecosystem/tools/ found here https://github.com/covesa/vss-tools .

**Comment by cjmodi306** [comment]
Okay, thank you for the support. I'll try it and notify the results.

**Comment by cjmodi306** [comment]
It works! Thank you for your support.
