### ISSUE TITLE
TypeError for custom DBC Mapping

### ISSUE THREAD

**Issue by mikehaller** [eclipse-kuksa/kuksa-can-provider#30]
I am using a custom DBC, kuksa-can-provider 0.4.2 and a dbc2val mapping.

When I send the respective CAN Frame, the kuksa-can-provider / dbcfeeder throws the following error message during the conversion into a gRPC message. I assume that the actual reading from CAN (vcan0) was done correctly and the DBC is correct as well.

```
2024-09-18 14:37:10,977 ERROR dbcfeeder: Exception caught in main loop
Traceback (most recent call last):
  File "dbcfeeder.py", line 287, in _run_receiver
  File "dbcfeederlib/databrokerclientwrapper.py", line 182, in update_datapoint
  File "kuksa_client/grpc/__init__.py", line 676, in wrapper
  File "kuksa_client/grpc/__init__.py", line 913, in set
  File "kuksa_client/grpc/__init__.py", line 606, in _prepare_set_request
  File "kuksa_client/grpc/__init__.py", line 500, in to_message
  File "kuksa_client/grpc/__init__.py", line 460, in to_message
  File "kuksa_client/grpc/__init__.py", line 416, in to_message
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NamedSignalValue'
```

It seems that somewhere, a "value" object may be of an internal Python CAN-Tools object class, which is unsupported by gRPC value fields.

**Comment by erikbosch** [comment]
Could you try running in debug mode? I suspect that this is a signal where no transformation has been defined, then we currently just tries to pass the value to Databroker using Proto. That might work well for integer-style numbers, but likely not for named values like what we have at https://github.com/eclipse-kuksa/kuksa-can-provider/blob/main/Model3CAN.dbc#L3384

`VAL_ 258 VCLEFT_frontLatchStatus 5 "LATCH_AJAR" 2 "LATCH_CLOSED" 3 "LATCH_CLOSING" 7 "LATCH_DEFAULT" 8 "LATCH_FAULT" 1 "LATCH_OPENED" 4 "LATCH_OPENING" 0 "LATCH_SNA" 6 "LATCH_TIMEOUT" ;`

Then one could discuss what CAN-Provider shall do in this case if there is no transformation definition. Shall it assume that the numerical value is the one to use, or that the string value is the one to use, or try to be smart checking the VSS signal (i.e. use int if VSS signal uses int, ...), or simply refuse to do automatic mapping and give error. A workaround for now is to use explicit mapping.

If you get the debug message above, could you check if your signal has named values similar to `VCLEFT_frontLatchStatus` above.

Suspected code:

```
       if self.transform is None:
            log.debug("No mapping to VSS %s, using raw value %s", self.vss_name, value)
            vss_value = value
```

We should better check if our default can dump file contain any named values so we could try to reproduce the error when doing can replay as part of our testing.
